import type { Category, CategoryId, CurrencyConfig, Transaction } from '../models/expense';

export const CATEGORIES: Record<CategoryId, Category> = {
  // Expense Categories
  food: {
    id: 'food',
    name: 'Food & Dining',
    icon: '🍔',
    color: '#f97316',
    bgLight: 'rgba(249, 115, 22, 0.15)',
    type: 'expense',
  },
  housing: {
    id: 'housing',
    name: 'Housing & Rent',
    icon: '🏠',
    color: '#6366f1',
    bgLight: 'rgba(99, 102, 241, 0.15)',
    type: 'expense',
  },
  transportation: {
    id: 'transportation',
    name: 'Transportation',
    icon: '🚗',
    color: '#06b6d4',
    bgLight: 'rgba(6, 182, 212, 0.15)',
    type: 'expense',
  },
  utilities: {
    id: 'utilities',
    name: 'Utilities & Bills',
    icon: '⚡',
    color: '#eab308',
    bgLight: 'rgba(234, 179, 8, 0.15)',
    type: 'expense',
  },
  entertainment: {
    id: 'entertainment',
    name: 'Entertainment',
    icon: '🎬',
    color: '#ec4899',
    bgLight: 'rgba(236, 72, 153, 0.15)',
    type: 'expense',
  },
  healthcare: {
    id: 'healthcare',
    name: 'Healthcare & Fitness',
    icon: '💊',
    color: '#10b981',
    bgLight: 'rgba(16, 185, 129, 0.15)',
    type: 'expense',
  },
  shopping: {
    id: 'shopping',
    name: 'Shopping',
    icon: '🛍️',
    color: '#8b5cf6',
    bgLight: 'rgba(139, 92, 246, 0.15)',
    type: 'expense',
  },

  // Income Categories
  salary: {
    id: 'salary',
    name: 'Monthly Salary',
    icon: '💼',
    color: '#10b981',
    bgLight: 'rgba(16, 185, 129, 0.15)',
    type: 'income',
  },
  freelance: {
    id: 'freelance',
    name: 'Freelance & Consulting',
    icon: '💻',
    color: '#3b82f6',
    bgLight: 'rgba(59, 130, 246, 0.15)',
    type: 'income',
  },
  investment: {
    id: 'investment',
    name: 'Investments & Dividends',
    icon: '📈',
    color: '#8b5cf6',
    bgLight: 'rgba(139, 92, 246, 0.15)',
    type: 'income',
  },
  gift: {
    id: 'gift',
    name: 'Gifts & Bonuses',
    icon: '🎁',
    color: '#f59e0b',
    bgLight: 'rgba(245, 158, 11, 0.15)',
    type: 'income',
  },
  other_income: {
    id: 'other_income',
    name: 'Other Income',
    icon: '💵',
    color: '#10b981',
    bgLight: 'rgba(16, 185, 129, 0.15)',
    type: 'income',
  },
  other: {
    id: 'other',
    name: 'Other',
    icon: '📦',
    color: '#64748b',
    bgLight: 'rgba(100, 116, 139, 0.15)',
    type: 'expense',
  },
};

export const CATEGORY_LIST: Category[] = Object.values(CATEGORIES);

export const EXPENSE_CATEGORIES = CATEGORY_LIST.filter((c) => c.type === 'expense');
export const INCOME_CATEGORIES = CATEGORY_LIST.filter((c) => c.type === 'income');

export const SUPPORTED_CURRENCIES: CurrencyConfig[] = [
  { code: 'USD', symbol: '$', label: 'USD ($)' },
  { code: 'EUR', symbol: '€', label: 'EUR (€)' },
  { code: 'GBP', symbol: '£', label: 'GBP (£)' },
  { code: 'INR', symbol: '₹', label: 'INR (₹)' },
  { code: 'JPY', symbol: '¥', label: 'JPY (¥)' },
  { code: 'CAD', symbol: 'CA$', label: 'CAD (CA$)' },
  { code: 'AUD', symbol: 'AU$', label: 'AUD (AU$)' },
];

export const DEFAULT_CURRENCY = '$';

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: 'sample-inc-1',
    title: 'Primary Tech Job Salary',
    amount: 3800.00,
    type: 'income',
    categoryId: 'salary',
    date: '2026-09-01',
    notes: 'Direct deposit bi-weekly salary',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 16,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 16,
  },
  {
    id: 'sample-inc-2',
    title: 'Design System Consulting',
    amount: 650.00,
    type: 'income',
    categoryId: 'freelance',
    date: '2026-09-10',
    notes: 'Freelance UI audit client payout',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
  {
    id: 'sample-exp-1',
    title: 'Apartment Monthly Rent',
    amount: 1250.00,
    type: 'expense',
    categoryId: 'housing',
    date: '2026-09-02',
    notes: 'Downtown 1-bedroom rent',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
  },
  {
    id: 'sample-exp-2',
    title: 'Whole Foods Grocery Haul',
    amount: 142.50,
    type: 'expense',
    categoryId: 'food',
    date: '2026-09-14',
    notes: 'Weekly fresh produce & pantry items',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: 'sample-exp-3',
    title: 'Fiber Internet Subscription',
    amount: 65.00,
    type: 'expense',
    categoryId: 'utilities',
    date: '2026-09-05',
    notes: 'Gigabit fiber connection',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    id: 'sample-exp-4',
    title: 'Electric Vehicle Charging',
    amount: 32.40,
    type: 'expense',
    categoryId: 'transportation',
    date: '2026-09-12',
    notes: 'Fast charging station',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: 'sample-exp-5',
    title: 'Cinema & IMAX Night',
    amount: 38.00,
    type: 'expense',
    categoryId: 'entertainment',
    date: '2026-09-13',
    notes: 'Movie tickets and snack combo',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: 'sample-exp-6',
    title: 'Gym & Wellness Pass',
    amount: 55.00,
    type: 'expense',
    categoryId: 'healthcare',
    date: '2026-09-04',
    notes: 'Monthly gym and recovery access',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 13,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 13,
  },
];
